# Generated by Django 5.0.4 on 2024-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteurs',
            name='photo',
            field=models.CharField(default='default.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='jeux',
            name='photo',
            field=models.CharField(default='default.jpg', max_length=100),
        ),
    ]
