# Generated by Django 5.0.4 on 2024-05-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0002_auteurs_photo_jeux_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListeJeuJoueur',
            new_name='ListeJeuxJoueurs',
        ),
    ]
