# Generated by Django 5.0.4 on 2024-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0003_rename_listejeujoueur_listejeuxjoueurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
