# Generated by Django 5.0.4 on 2024-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0004_alter_jeux_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
