# Generated by Django 5.0.4 on 2024-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0005_alter_jeux_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='anneeSortie',
            field=models.IntegerField(max_length=5),
        ),
    ]
