# Generated by Django 5.0.4 on 2024-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0006_alter_jeux_anneesortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='anneeSortie',
            field=models.IntegerField(),
        ),
    ]
