# Generated by Django 5.0.4 on 2024-06-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0007_alter_jeux_anneesortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteurs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
