# Generated by Django 5.0.4 on 2024-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0008_alter_auteurs_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='note',
            field=models.FloatField(max_length=3),
        ),
        migrations.RemoveField(
            model_name='listejeuxjoueurs',
            name='jeux',
        ),
        migrations.RemoveField(
            model_name='listejeuxjoueurs',
            name='joueurs',
        ),
        migrations.AddField(
            model_name='listejeuxjoueurs',
            name='jeux',
            field=models.ManyToManyField(to='ludotheque.jeux'),
        ),
        migrations.AddField(
            model_name='listejeuxjoueurs',
            name='joueurs',
            field=models.ManyToManyField(to='ludotheque.joueurs'),
        ),
    ]
