# Generated by Django 5.0.4 on 2024-06-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0009_alter_commentaires_note_remove_listejeuxjoueurs_jeux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeux',
            name='joueurs',
            field=models.ManyToManyField(through='ludotheque.ListeJeuxJoueurs', to='ludotheque.joueurs'),
        ),
        migrations.RemoveField(
            model_name='listejeuxjoueurs',
            name='jeux',
        ),
        migrations.RemoveField(
            model_name='listejeuxjoueurs',
            name='joueurs',
        ),
        migrations.AddField(
            model_name='listejeuxjoueurs',
            name='jeux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeux'),
        ),
        migrations.AddField(
            model_name='listejeuxjoueurs',
            name='joueurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueurs'),
        ),
    ]
